### PR TITLE
update jedis dependency from 2.1.0 to 2.2.0.  Alleviates issue in using ...

### PR DESCRIPTION
**Pull request by dtanner**
...this plugin and the latest redis plugin, as documented here:

https://github.com/xetorthio/jedis/issues/303

### CODE REVIEW

**Comment by burtbeckwith** [comment]
Thanks, I released v0.2 with this change

**Comment by dtanner** [comment]
Thanks Burt!

**Comment by dtanner** [comment]
My apologies - this alone didn't fix the problem.  I also needed to patch the tomcat-redis-session library; I needed to updated its jedis version dependency to 2.2.0 in its pom.xml.  I can submit that patch to the project, and then this plugin would need to get bumped up again for that change.

**Comment by tamershahin** [comment]
Thanks everybody.. I hope that they could updated the tomcat-redis-session library soon!

**Pull request merged**
